name: "Quarkus platform CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build-and-testing
    steps:
      - name: Checkout Quarkus Platform
        uses: actions/checkout@v2
        with:
          path: quarkus-platform
      - name: Checkout Quarkus
        uses: actions/checkout@v2
        with:
          repository: quarkusio/quarkus
          path: quarkus

